######################################################################
# Automatically generated by qmake (2.01a) Fri Oct 25 06:45:03 2013
######################################################################

TEMPLATE = subdirs

INCLUDEPATH += /opt/ros/groovy/include/

HEADERS += ../include/phi_ardrone/phi_pilot.h

SOURCES += ../src/phi_node_keyboard_pilot.cpp \
		   ../src/phi_pilot.cpp




# Directories
