######################################################################
# Automatically generated by qmake (2.01a) Thu Nov 7 17:33:01 2013
######################################################################

TEMPLATE = subdirs

INCLUDEPATH += /opt/ros/groovy/include/

HEADERS += ../include/phi_ardrone/phi_pilot.h \
		+= ../include/phi_ardrone/phi_point_follower.h

SOURCES += ../src/phi_node_point_follower.cpp \
		   ../src/phi_point_follower.cpp \
		   ../src/phi_pilot.cpp
