######################################################################
# Automatically generated by qmake (2.01a) Fri Oct 25 06:45:03 2013
######################################################################

TEMPLATE = subdirs

INCLUDEPATH += /opt/ros/groovy/include/

HEADERS += ../include/phi_ardrone/phi_pilot.h \
		+= ../include/phi_ardrone/phi_redball_tracker.h

SOURCES += ../src/phi_node_redball_tracker.cpp\
		   ../src/phi_redball_tracker.cpp




# Directories
